project('solar', ['c', 'cpp', 'fortran'], version: '9.0.1')

#libricvolume_proj = subproject('libRicVolume')
#libricvolume_dep = libricvolume_proj.get_variable('libricvolume')

libplinkio_proj = subproject('libplinkio')
libplinkio_dep = libplinkio_proj.get_variable('libplinkio')

#libsafe_proj = subproject('libsafe')
#libsafe_dep = libsafe_proj.get_variable('libsafe')
#
#libtcl_proj = subproject('libtcl', version: '8.4.20')
#libtcl_dep = libtcl_proj.get_variable('libtcl')

# FIXME: executable must be called here, not in subdir
#subdir('src/solarmain')
