SOURCE_PATH=/home/brian/solar_versions/solar-eclipse-9.0.1/bin_src/solarmain-9.0.0-test/src

CXX_OBJECTS= \
$(SOURCE_PATH)/genetic_correlation.o \
$(SOURCE_PATH)/alnormc.o \
$(SOURCE_PATH)/annotate_gwas.o \
$(SOURCE_PATH)/ccsearch.o \
$(SOURCE_PATH)/calculate_snp_frequencies.o \
$(SOURCE_PATH)/chi.o \
$(SOURCE_PATH)/constraint.o \
$(SOURCE_PATH)/covariate.o \
$(SOURCE_PATH)/create_evd.o \
$(SOURCE_PATH)/create_fake_pedigree.o \
$(SOURCE_PATH)/define.o \
$(SOURCE_PATH)/drand.o \
$(SOURCE_PATH)/eqvar.o \
$(SOURCE_PATH)/evd.o \
$(SOURCE_PATH)/expression.o \
$(SOURCE_PATH)/field.o \
$(SOURCE_PATH)/fisherpedigree.o \
$(SOURCE_PATH)/fphi.o \
$(SOURCE_PATH)/freq.o \
$(SOURCE_PATH)/function.o \
$(SOURCE_PATH)/gwas.o \
$(SOURCE_PATH)/help.o \
$(SOURCE_PATH)/howclose.o \
$(SOURCE_PATH)/ibd.o \
$(SOURCE_PATH)/ibdoption.o \
$(SOURCE_PATH)/ibs.o \
$(SOURCE_PATH)/inorm_nifti.o \
$(SOURCE_PATH)/key.o \
$(SOURCE_PATH)/listmaker.o \
$(SOURCE_PATH)/loadsave.o \
$(SOURCE_PATH)/loglike.o \
$(SOURCE_PATH)/map.o \
$(SOURCE_PATH)/marker.o \
$(SOURCE_PATH)/mathmatrix.o \
$(SOURCE_PATH)/matrix.o \
$(SOURCE_PATH)/maximize.o \
$(SOURCE_PATH)/mibd.o \
$(SOURCE_PATH)/model.o \
$(SOURCE_PATH)/mu.o \
$(SOURCE_PATH)/nifti_assemble.o \
$(SOURCE_PATH)/nifti_to_csv.o \
$(SOURCE_PATH)/normal.o \
$(SOURCE_PATH)/omega.o \
$(SOURCE_PATH)/option.o \
$(SOURCE_PATH)/parameter.o \
$(SOURCE_PATH)/pedifromsnps.o \
$(SOURCE_PATH)/pedigree.o \
$(SOURCE_PATH)/phenotypes.o \
$(SOURCE_PATH)/plink_converter.o \
$(SOURCE_PATH)/power.o \
$(SOURCE_PATH)/reorder_phenotype.o \
$(SOURCE_PATH)/scale.o \
$(SOURCE_PATH)/scan.o \
$(SOURCE_PATH)/scratchfile.o \
$(SOURCE_PATH)/simqtl.o \
$(SOURCE_PATH)/snp.o \
$(SOURCE_PATH)/solar.o \
$(SOURCE_PATH)/solarfile.o \
$(SOURCE_PATH)/solarfilecmd.o \
$(SOURCE_PATH)/solar_mle_setup.o \
$(SOURCE_PATH)/solar-trait-reader.o \
$(SOURCE_PATH)/split_pheno_file.o \
$(SOURCE_PATH)/sporadic.o \
$(SOURCE_PATH)/tablefile.o \
$(SOURCE_PATH)/tablefilecmd.o \
$(SOURCE_PATH)/token.o \
$(SOURCE_PATH)/trait.o \
$(SOURCE_PATH)/verbosity.o \
$(SOURCE_PATH)/voxel.o \
$(SOURCE_PATH)/zscore.o \

C_OBJECTS= \
$(SOURCE_PATH)/ccuserid.o \
$(SOURCE_PATH)/cplink_converter.o \
$(SOURCE_PATH)/eigstruc.o \
$(SOURCE_PATH)/fdate.o \
$(SOURCE_PATH)/mehd.o \
$(SOURCE_PATH)/ncdf.o \
$(SOURCE_PATH)/npdf.o \
$(SOURCE_PATH)/nrutil.o \
$(SOURCE_PATH)/plotpipe.o \
$(SOURCE_PATH)/safelib.o \
$(SOURCE_PATH)/solarmain.o \
$(SOURCE_PATH)/tclgr.o \
$(SOURCE_PATH)/w_mehd.o \

FC_OBJECTS= \
$(SOURCE_PATH)/alnorm.o \
$(SOURCE_PATH)/astop.o \
$(SOURCE_PATH)/asycov.o \
$(SOURCE_PATH)/beta.o \
$(SOURCE_PATH)/calc.o \
$(SOURCE_PATH)/cdfchi.o \
$(SOURCE_PATH)/cdfnor.o \
$(SOURCE_PATH)/chisq.o \
$(SOURCE_PATH)/clear.o \
$(SOURCE_PATH)/copyped.o \
$(SOURCE_PATH)/covar.o \
$(SOURCE_PATH)/dasycov.o \
$(SOURCE_PATH)/dcopyped.o \
$(SOURCE_PATH)/dcovar.o \
$(SOURCE_PATH)/ddfun.o \
$(SOURCE_PATH)/delta7.o \
$(SOURCE_PATH)/dfun.o \
$(SOURCE_PATH)/digam.o \
$(SOURCE_PATH)/direct.o \
$(SOURCE_PATH)/dmean.o \
$(SOURCE_PATH)/dppfa.o \
$(SOURCE_PATH)/edftst.o \
$(SOURCE_PATH)/evdlik.o \
$(SOURCE_PATH)/evdout.o \
$(SOURCE_PATH)/fdist.o \
$(SOURCE_PATH)/fit2dp.o \
$(SOURCE_PATH)/fortfiles.o \
$(SOURCE_PATH)/fpedifromsnps.o \
$(SOURCE_PATH)/fun.o \
$(SOURCE_PATH)/fun_mehd.o \
$(SOURCE_PATH)/gamlog.o \
$(SOURCE_PATH)/gaucdf.o \
$(SOURCE_PATH)/hessin.o \
$(SOURCE_PATH)/hpsort.o \
$(SOURCE_PATH)/inital.o \
$(SOURCE_PATH)/ipmpar.o \
$(SOURCE_PATH)/kin.o \
$(SOURCE_PATH)/linpack.o \
$(SOURCE_PATH)/logo.o \
$(SOURCE_PATH)/loop.o \
$(SOURCE_PATH)/mblank.o \
$(SOURCE_PATH)/mvncdf.o \
$(SOURCE_PATH)/newlik.o \
$(SOURCE_PATH)/optima.o \
$(SOURCE_PATH)/output.o \
$(SOURCE_PATH)/pedtst.o \
$(SOURCE_PATH)/phidens.o \
$(SOURCE_PATH)/pinput.o \
$(SOURCE_PATH)/ppnd.o \
$(SOURCE_PATH)/preopt.o \
$(SOURCE_PATH)/preped.o \
$(SOURCE_PATH)/qdprog.o \
$(SOURCE_PATH)/random.o \
$(SOURCE_PATH)/resid.o \
$(SOURCE_PATH)/scor.o \
$(SOURCE_PATH)/search.o \
$(SOURCE_PATH)/settab.o \
$(SOURCE_PATH)/smpoutput.o \
$(SOURCE_PATH)/spmpar.o \
$(SOURCE_PATH)/sweep.o \
$(SOURCE_PATH)/symeig.o \
$(SOURCE_PATH)/tdist.o \
$(SOURCE_PATH)/trigam.o \
$(SOURCE_PATH)/upcase.o \
$(SOURCE_PATH)/writestr.o \
$(SOURCE_PATH)/yesno.o \

HEADERS= \
$(SOURCE_PATH)/config.h \
$(SOURCE_PATH)/expression.h \
$(SOURCE_PATH)/mvn.h \
$(SOURCE_PATH)/nrutil.h \
$(SOURCE_PATH)/plotpipe.h \
$(SOURCE_PATH)/solar.h \
$(SOURCE_PATH)/solar_mle_setup.h \
$(SOURCE_PATH)/solar-trait-reader.h \
$(SOURCE_PATH)/tablefile.h \
$(SOURCE_PATH)/token.h \

LIBRARIES= \
/home/brian/solar_versions/solar-eclipse-9.0.1/bin_src/solarmain-9.0.0-test/lib/libsafe.a \
/home/brian/solar_versions/solar-eclipse-9.0.1/bin_src/solarmain-9.0.0-test/lib/libRicVolume.a \
/home/brian/solar_versions/solar-eclipse-9.0.1/bin_src/solarmain-9.0.0-test/lib/libplinkio.a \
/home/brian/solar_versions/solar-eclipse-9.0.1/bin_src/solarmain-9.0.0-test/lib/libtcl8.4.a \
-ldl \
-lstdc++ \

MKL_LIBS= \
