INCLUDES= \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-data.h \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-exception.h \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-fphi-settings.h \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-fphi-variables.h \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-gwas-estimator-context.h \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-gwas-estimator.h \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-gwas.h \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-gwas-screen-variables.h \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-gwas-settings.h \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-pedigree-data.h \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-selection.h \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/solar-trait-reader.h \
 
OBJECTS= \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-fphi.o \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-fphi-command.o \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-fphi-variables.o \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-gwas.o \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-gwas-command.o \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-gwas-estimator.o \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-gwas-estimator-context.o \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-gwas-screen.o \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-gwas-screen-variables.o \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-pedifromsnps.o \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-pedigree-data.o \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-selection.o \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-pedifromsnps-kernels.o \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-fphi-kernels.o \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-gwas-kernels.o \
/home/brian/solar_versions/solar-eclipse-9.0.1/lib_src/libgpu-commands/src/gpu-gwas-screen-kernels.o \
